mygames/game/urls.py
from django.urls import path
from . import views

app_name = 'demo_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('games/', views.games, name='games'),
    path('game/<int:id>', views.game, name='game'),
    path('game/edit/<int:id>', views.edit, name='edit'),
    path('game/new/', views.new, name='new'),
    path('games/best/', views.best, name='best'),
    path('games/worst/', views.worst, name='worst'),
    path('games/average/', views.average, name='average'),
    path('games/count/', views.count, name='count'),
    path('games/summarize/', views.summarize, name='summarize'),
    path('signup/', views.signup, name='signup'),
]

mygames/mygames/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls'))
]

mygames/game/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


def validate_release_year(value):
    if 1950 > value > 2021:
        return ValidationError('That year is not valid')
    else:
        return value


def validate_grade(value):
    if 0 > value > 10:
        return ValidationError('Your grade is not valid, please use values from 0 to 10')
    else:
        return value


class Game(models.Model):
    title = models.CharField(max_length=50, default='')
    GAME_GENRE = [
        ('AC', 'Action'),
        ('AA', 'Action-adventure'),
        ('AD', 'Adventure'),
        ('RP', 'Role-Playing'),
        ('SI', 'Simulation'),
        ('ST', 'Strategy'),
        ('SP', 'Sports'),
        ('MM', 'MMO'),
        ('SB', 'Sandbox')
    ]
    genre = models.CharField(blank=True, choices=GAME_GENRE, max_length=2, default='')
    release_year = models.IntegerField(blank=True, validators=[validate_release_year])
    comment = models.TextField(help_text='your comment', default='')
    grade = models.IntegerField(default=0, validators=[validate_grade])
    would_recommend = models.BooleanField(default=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=2)

    def __str__(self):
        return self.title

mygames/game/forms.py
from django.forms import ModelForm
from .models import Game
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class GameForm(ModelForm):
    class Meta:
        model = Game
        fields = ['title', 'genre', 'release_year', 'comment', 'grade', 'would_recommend']


# class SignUpForm(UserCreationForm):
#     first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
#     last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
#     email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
#
#     class Meta:
#         model = User
#         fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

mygames/game/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Game
from .forms import GameForm
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Avg, Max, Min, Count, Sum


def index(req):
    if not req.user.is_authenticated:
        return render(req, 'index.html', {'page_title': 'Home Page'})
    else:
        return redirect('demo_app:games')


@login_required
def games(req):
    collection = Game.objects.all()
    return render(req, 'games.html', {'games': collection})


@login_required
def game(req, id):
    # gobject : game_object
    gobject = get_object_or_404(Game, id=id)
    return render(req, 'game.html', {'game': gobject, 'page_title': gobject.title})


# --=}_{==!|?|!==}_({=--  AGGREGATION  --=})_{==!|?|!==}_{=-- #


@login_required
def best(req):
    collection = Game.objects.all().aggregate(Max('grade'))
    maxVal = collection['grade__max']
    collection = Game.objects.all().filter(grade=maxVal)
    return render(req, 'aggreg_max_min.html', {'games': collection, 'grade': maxVal})


@login_required
def worst(req):
    collection = Game.objects.all().aggregate(Min('grade'))
    minVal = collection['grade__min']
    collection = Game.objects.all().filter(grade=minVal)
    return render(req, 'aggreg_max_min.html', {'games': collection, 'grade': minVal})


@login_required
def count(req):
    collection = Game.objects.all().aggregate(Count('grade'))
    avg = collection['grade__count']
    return render(req, 'aggreg_count.html', {'count': avg})


@login_required
def average(req):
    collection = Game.objects.all().aggregate(Avg('grade'))
    avg = collection['grade__avg']
    collection = Game.objects.count()
    return render(req, 'aggreg_avg.html', {'count': collection, 'average': avg})


@login_required
def summarize(req):
    collection = Game.objects.all().aggregate(Sum('grade'))
    sum = collection['grade__sum']
    collection = Game.objects.count()
    return render(req, 'aggreg_sum.html', {'count': collection, 'sum': sum})


@permission_required('game.change_game')
def edit(req, id):
    if req.method == 'POST':
        form = GameForm(req.POST)

        if form.is_valid():
            game = Game.objects.get(id=id)
            game.title = form.cleaned_data['title']
            game.comment = form.cleaned_data['comment']
            game.release_year = form.cleaned_data['release_year']
            game.would_recommend = form.cleaned_data['would_recommend']
            game.save()
            return redirect('demo_app:games')
        else:
            return render(req, 'edit.html', {'form': form, 'id': id})
    else:
        game = Game.objects.get(id=id)
        form = GameForm(instance=game)
        return render(req, 'edit.html', {'form': form, 'id': id})


@permission_required('game.add_game')
def new(req):
    if req.method == 'POST':
        form = GameForm(req.POST)

        if form.is_valid():
            game = Game(title=form.cleaned_data['title'], comment=form.cleaned_data['comment'], release_year=form.cleaned_data['release_year'], reccomend=form.cleaned_data['would_recommend'], owner=req.user)
            game.save()
            return redirect('demo_app:games')
        else:
            return render(req, 'new.html', {'form': form})
    else:
        form = GameForm()
        return render(req, 'new.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            user.save()
            login(request, user)
            return redirect('demo_app:games')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

mygames/game/templates/aggreg_avg.html
{%  extends 'master.html' %}

{% block title %}
    Average
{% endblock %}

{%  block content %}
    <div>
        Your average grade for <b>{{ count }}</b> games is: <b>{{ average }}</b>.
    </div>
{% endblock %}

mygames/game/templates/aggreg_count.html
{%  extends 'master.html' %}

{% block title %}
    Count
{% endblock %}

{%  block content %}
    <div>
        Your have reviewed <b>{{ count }}</b> games.
    </div>
{% endblock %}

mygames/game/templates/aggreg_max_min.html
{%  extends 'master.html' %}

{% block title %}
    Grades
{% endblock %}

{%  block content %}
    <div>
        Grade: {{ grade }}
    </div>
    <div class="list-group">
        {% for game in games %}
            <a class="list-group-item list-group-item-action" href="{% url 'demo_app:game' game.id %}">
                {{ game.title }}
            </a>
        {% endfor %}
    </div>
{% endblock %}

mygames/game/templates/aggreg_sum.html
{%  extends 'master.html' %}

{% block title %}
    Count
{% endblock %}

{%  block content %}
    <div>
        The sum of all your grades is <b>{{ sum }}</b> for <b>{{ count }}</b> games you rated.
        You can find what the average grade is in <i>/games/average</i>.
    </div>
{% endblock %}

mygames/game/templates/edit.html
{% extends 'master.html' %}

{% block title %}
    Edit game
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'demo_app:edit' id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.name }}" value="{{ form.title.value }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.comment.id_for_label }}">{{ form.comment.label_tag }}</label>
            <textarea class="form-control" id="{{ form.comment.id_for_label }}" name="{{ form.comment.name }}" rows="5">{{ form.comment.value }}</textarea>
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.release_year.id_for_label }}">{{ form.release_year.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.release_year.id_for_label }}" name="{{ form.release_year.name }}" value="{{ form.release_year.value }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.would_recommend.id_for_label }}">{{ form.would_recommend.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.would_recommend.id_for_label }}" name="{{ form.would_recommend.name }}" value="{{ form.would_recommend.value }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn-dark btn-lg" value="save changes"/>
    </form>

{% endblock %}

mygames/game/templates/game.html
{% extends 'master.html' %}

{% block content %}

    <div class="card">
        <div class="card-header">
            <h1>
                {{ game.title }}
                [{{ game.release_year }}]
                {% if perms.game.change_game %}
                    <a href="{% url 'demo_app:edit' game.id %}">
                        <span class="badge btn-dark">Edit</span>
                    </a>
                {% endif %}
            </h1>
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>{{ game.comment }}</p>
                <p>Would you recommend this game?
                    {{ game.would_recommend }}
                </p>
                <footer class="blockquote-footer">
                    Author:
                    <cite title="Source Title">
                        {{ game.owner }}
                    </cite>
                </footer>
            </blockquote>
        </div>
    </div>

{% endblock %}

mygames/game/templates/games.html
{%  extends 'master.html' %}

{% block title %}
    Games
{% endblock %}

{%  block content %}
    <div class="list-group">
        {% for game in games %}
            <a class="list-group-item list-group-item-action" href="{% url 'demo_app:game' game.id %}">
                {{ game.title }}
            </a>
        {% endfor %}
    </div>
{% endblock %}

mygames/game/templates/index.html
{%  extends 'master.html' %}

{%  block content %}
    <p>You are not logged in.</p>
    <a href="{% url 'login'%}">Click here to login.</a>
{% endblock %}

mygames/game/templates/new.html
{% extends 'master.html' %}

{% block title %}
    New game
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'demo_app:new' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.name }}" value="{{ form.title.value }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.comment.id_for_label }}">{{ form.comment.label_tag }}</label>
            <textarea class="form-control" id="{{ form.comment.id_for_label }}" name="{{ form.comment.name }}" rows="5">{{ form.comment.value }}</textarea>
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.release_year.id_for_label }}">{{ form.release_year.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.release_year.id_for_label }}" name="{{ form.release_year.name }}" value="{{ form.release_year.value }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.would_recommend.id_for_label }}">{{ form.would_recommend.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.would_recommend.id_for_label }}" name="{{ form.would_recommend.name }}" value="{{ form.would_recommend.value }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn-dark btn-lg" value="save changes"/>
    </form>

{% endblock %}

mygames/game/templates/register.html
<!--{% extends 'master.html' %}-->

<!--{% block content %}-->
<!--  <h2>Sign up</h2>-->
<!--  <form method="post">-->
<!--    {% csrf_token %}-->
<!--    {% for field in form %}-->
<!--      <p>-->
<!--        {{ field.label_tag }}<br>-->
<!--        {{ field }}-->
<!--        {% if field.help_text %}-->
<!--          <small style="color: grey">{{ field.help_text }}</small>-->
<!--        {% endif %}-->
<!--        {% for error in field.errors %}-->
<!--          <p style="color: red">{{ error }}</p>-->
<!--        {% endfor %}-->
<!--      </p>-->
<!--    {% endfor %}-->
<!--    <button type="submit">Sign up</button>-->
<!--  </form>-->
<!--{% endblock %}-->

mygames/game/templates/signup.html
{% extends 'master.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

mygames/templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'demo_app:games' %}">
        <img src="{% static 'img/joystick.png' %}" width="30" height="30" class="d-inline-block align-top" alt="logo"/>
        MyGameLibrary
    </a>

    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            {% if not perms.game.add_game %}
                <a class="nav-link disabled" href="{% url 'demo_app:new' %}">New Game</a>
            {% else %}
                <a class="nav-link" href="{% url 'demo_app:new' %}">New Game</a>
            {% endif %}
        </li>
    </ul>

    {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Logout {{ user.get_username }}</a>
    {% endif %}

</nav>

mygames/templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>
            {% block title %}
                {{ page_title|default:"Untitled Page" }}
            {% endblock title %}
        </title>

        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    </head>

    <body>

        {% include 'header.html' %}

        <div class="container" style="text-align: center; margin-top: 50px">
            {% block content %}
                <p>Placeholder text in base template. Replace with page content.</p>
            {% endblock content %}
        </div>

    </body>
</html>